version: "3.8"

services:

  accounts:
    image: lukegrossmann/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - lukegrossmann-network
    
  loans:
    image: lukegrossmann/loans:latest
    ports:
      - "8090:8090"
    networks:
      - lukegrossmann-network
    
  cards:
    image: lukegrossmann/cards:latest
    ports:
      - "9000:9000"
    networks:
      - lukegrossmann-network
    
networks:
  lukegrossmann-network: