version: "3.8"

services:

  configserver:
    image: lukegrossmann/configserver:latest
    ports:
      - "8071:8071"
    networks:
     - lukegrossmann
      
  accounts:
    image: lukegrossmann/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - lukegrossmann
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  
  loans:
    image: lukegrossmann/loans:latest
    ports:
      - "8090:8090"
    networks:
      - lukegrossmann
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  cards:
    image: lukegrossmann/cards:latest
    ports:
      - "9000:9000"
    networks:
      - lukegrossmann
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
networks:
  lukegrossmann: